### ISSUE TITLE
Cannot find tfx-cli error

### ISSUE THREAD

**Issue by jmezach** [jessehouwing/vsts-extension-tasks#22]
After using this extension for a while without problem I'm now all of a sudden getting errors like these:

```
2016-04-02T00:43:52.6673217Z ##[error]System.Management.Automation.RuntimeException: Unable to locate tfx ---> System.Management.Automation.RuntimeException: Unable to locate tfx
2016-04-02T00:43:52.6683180Z ##[error]   --- End of inner exception stack trace ---
2016-04-02T00:43:52.6693178Z ##[error]   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2016-04-02T00:43:52.6693178Z ##[error]   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2016-04-02T00:43:52.6703178Z ##[error]   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2016-04-02T00:43:52.6703178Z ##[error]   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-04-02T00:43:52.6713178Z ##[error]   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2016-04-02T00:43:52.6713178Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Handlers.PowerShellHandler.Execute(ITaskContext context, CancellationToken cancellationToken)
2016-04-02T00:43:52.6713178Z ##[error]   at Microsoft.TeamFoundation.DistributedTask.Worker.JobRunner.RunTask(ITaskContext context, TaskWrapper task, CancellationTokenSource tokenSource)
```

I've attached the full logs as well.
[logs_62.zip](https://github.com/jessehouwing/vsts-extension-tasks/files/200639/logs_62.zip)

**Comment by jessehouwing** [comment]
Hmz seems an interesting combination of factors. I don't really get why powershell suddenly has different serialization limits...

And it seems I need to setup builds for all the types of ways tfx can be installed and detected when accepting pull requests :).
